language:       cpp
compiler:       g++
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - VERSION=0.9.0
  - >
    COMMONFLAGS=
    --name          'helm'
    --description   'Polyphonic synthesizer'
    --version       $VERSION
    --package       helm_VERSION_ARCH.deb
    --license       'GPLv3'
    --maintainer    'matthewtytel@gmail.com'
    --vendor        'Matt Tytel'
    --url           'http://tytel.org/helm'
    --depends       'mesa-common'
    --depends       'libasound2'
    --depends       'libfreetype6'
    --depends       'libx11'
    --depends       'libxrandr'
    --depends       'libxinerama'
    --depends       'libxcursor'
    --depends       'freeglut3'
    --depends       'libxcomposite'
    --depends       'libjack'
    --depends       'libcurl4-gnutls'
    --category      'sound'
  - sudo apt-get update -qq
  - eval "${MATRIX_EVAL}"
  - sudo apt-get install -y mesa-common-dev libasound2-dev libfreetype6-dev
                            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev
                            freeglut3-dev libxcomposite-dev libjack-dev
                            libcurl4-gnutls-dev g++-4.8 gcc-4.8
  - gem install --no-rdoc --no-ri fpm package_cloud
  - mkdir dest
script:         >
  make CONFIG=Release install_standalong DESTDIR=dest                              &&
  fpm -s dir -t deb --name helm $COMMONFLAGS                                        \
    --deb-changelog debian/changelog                                                \
    --deb-priority  'optional'                                                      \
    dest/                                                                          &&
  echo "deb package built successfully"
after_success:
