language:       cpp
compiler:       clang
before_install:
  - VERSION=0.9.0
  - sudo apt-get update -qq
  - sudo apt-get install -y mesa-common-dev libasound2-dev libfreetype6-dev
                            libx11-dev libxrandr-dev libxinerama-dev libxcursor-dev
                            freeglut3-dev libxcomposite-dev libjack-dev
                            libcurl4-gnutls-dev
  - gem install --no-rdoc --no-ri fpm
script:         >
  make CONFIG=Release                                                              &&
  fpm -s dir -t deb --name helm --version $VERSION                                  \
    --package       helm_VERSION_ARCH.deb                                           \
    --license       'GPLv3'                                                         \
    --maintainer    'matthewtytel@gmail.com'                                        \
    --vendor        'Matt Tytel'                                                    \
    --url           'http://tytel.org/helm'                                         \
    --depends       'mesa-common'                                                   \
    --depends       'libasound2'                                                    \
    --depends       'libfreetype6'                                                  \
    --depends       'libx11'                                                        \
    --depends       'libxrandr'                                                     \
    --depends       'libxinerama'                                                   \
    --depends       'libxcursor'                                                    \
    --depends       'freeglut3'                                                     \
    --depends       'libxcomposite'                                                 \
    --depends       'libjack'                                                       \
    --depends       'libcurl4-gnutls'                                               \
    --description   'Polyphonic synthesizer'                                        \
    --deb-changelog debian/changelog                                                \
    --deb-priority  'optional'                                                      \
    --category      'sound'                                                         \
    usr/                                                                           &&
  echo "deb package built successfully"
after_success:
